# 실험 1 · 단계 0 — 데이터셋 조립 + 마스크 통계 (v2)

MoE 학습 전, 세 축(조리·향미·전통)의 실측 커버리지를 측정했습니다.
**조리 축 = RecipeDB 430개** (RecipeNLG 아님). 향미 축 = FlavorGraph cosine + FlavorDB rank.
후보는 **264개 그대로 유지**(축소 안 함).

> ## 판정: ✅ 전통 축 정상 작동 — 264 후보 그대로 진행
> positive 쌍의 mask_prop = **65.6%** (완비→부분보유 완화 후 53.3% → 65.6%)

이 v2는 사용자 지시 3건을 반영한 재빌드입니다: **[1] 성미 마스크 분할**, **[2] 라벨 정규화**,
**[3] pos_weight 재계산**.

---

## [1] 성미 완비 기준 완화 — 마스크 분할

이전엔 성·미·귀경을 **모두** 갖춘 81개만 `mask_prop=1`이었습니다. feature별로 부분 계산이
가능하므로 마스크를 쪼갰습니다.

```
mask_qi   = A·B 둘 다 성(性) 보유
mask_wei  = A·B 둘 다 미(味) 보유
mask_gui  = A·B 둘 다 귀경(歸經) 보유
mask_prop = 위 셋 중 하나라도 1        (expert 활성 조건)
```

결측 feature는 0으로 채우고, `miss_qi`/`miss_wei`/`miss_gui` 컬럼으로 무엇이 결측인지 기록.

### 탈락 30개의 원인 — 전부 귀경(歸經) 결손

완비(81) → 부분보유(any) 완화로 **+30개**가 살아납니다. 탈락했던 30개는 **예외 없이 귀경만
없고 성·미는 보유**한 재료였습니다.

> 사과·버터·로즈마리·셀러리·코코넛밀크·월계수·딜·타임·커민·참기름·오레가노·차·계란·바나나·
> 코코넛·딸기·망고·고구마·감자·녹차·깨·소금·아보카도·귀리·아티초크·커피·홍차·비트·토란·곤약

전부 **식품·향신료**로, TCM-MKG D7에 귀경 정보가 없는 재료입니다(성·미는 있음).
성(qi)·미(wei) feature는 온전히 계산되므로, 이들을 mask_prop=0으로 버리는 것은 정보 손실이었습니다.

### 완화 후 커버리지 상승

| 마스크 | 전체 | positive 중 |
|---|---|---|
| mask_qi | 1,443 (39.0%) | 330 (65.6%) |
| mask_wei | 1,443 (39.0%) | 330 (65.6%) |
| mask_gui | 1,053 (28.5%) | 258 (51.3%) |
| **mask_prop (any)** | 1,443 (39.0%) | **330 (65.6%)** |

성·미는 세트로 존재(같은 111개 재료), 귀경만 81개로 적습니다. **mask_prop이 53.3% → 65.6%로
상승**해 판정이 조건부에서 정상으로 바뀌었습니다.

---

## [2] 라벨 수 확인 — 표기 변형이 원인

14×20=280 기대인데 이전엔 Claude 251·Llama 244였습니다. 원인을 추적한 결과 **herb 자기 제외나
풀 누락이 아니라 표기 변형**이었습니다.

각 LLM 원본은 정확히 280개(GPT만 herb 자신 1건 포함)입니다. 문제는 라벨 매칭 시 후보 정규화를
안 해서, 아래 같은 변형이 264 후보에 못 붙은 것이었습니다:

| LLM 표기 | 실제 후보 | |
|---|---|---|
| 흑설탕 | 설탕 | 동의어 |
| 쌀식초 | 식초 | 동의어 |
| 미소된장 | 된장 | 동의어 |
| 참깨·흑임자 | 깨 | 동의어 |
| 삼겹살·돼지갈비 | 돼지고기 | 동의어 |
| 대추차 블렌드(계화) | (괄호 제거) | 정규화 |

라벨 매칭에도 후보와 **동일한 정규화**(괄호 제거 + 동의어 통합 + herb 자기 제외)를 적용했습니다.

### 복구 결과

| LLM | 이전 | **정규화 후** |
|---|---:|---:|
| Claude | 251 | **279** |
| Llama | 244 | **275** |
| GPT | 263 | **278** |

280에 근접합니다. 남은 소수(Claude 1, Llama 5, GPT 2)는 후보 264에 아예 없는 재료입니다
— 예: 카이란(중국브로콜리), 리크(대파), 월계수잎(허브 자신), 진피. 이들은 264 pool 밖이라
정상적으로 제외됩니다.

---

## [3] pos_weight 재계산 — 세 축 부재 제외

세 축 모두 부재인 1,373쌍은 학습에서 제외되므로, 실제 학습 대상의 positive rate로 계산했습니다.

| | 전체 | **학습 대상 (부재 제외)** |
|---|---:|---:|
| 쌍 수 | 3,696 | **2,323** |
| positive | 503 | **438** |
| positive rate | 13.61% | **18.85%** |
| **pos_weight (neg/pos)** | — | **4.304** |

예상대로 **약 19%**입니다(전체 13.6%가 아님). 학습 시 `pos_weight=4.30`을 loss에 적용하면 됩니다.

---

## 작업 2 — 데이터셋

`exp1_dataset.csv` — **3,696행** (14 herbs × 264 candidates), **23컬럼**.

```
herb, candidate,
cook_count, cook_rank_inv, cook_pmi,           # 조리 3
fg_cosine, fdb_rank_inv,                        # 향미 2
qi_diff, qi_B, wei_jac, gui_jac,                # 전통 4
mask_cook, mask_flavor, mask_qi, mask_wei, mask_gui, mask_prop,   # 마스크 6
miss_qi, miss_wei, miss_gui,                    # 결측 기록 3
label_claude, label_llama, label_gpt           # 라벨 3
```

- 조리 PPMI 분모는 RecipeDB 430 내부 추정(표본 작아 노이즈 있음, 명시).
- 향미 herb 노드: 연꽃→`lotus_seed`, 우엉→`burdock_root` 교정 후 14개 전부 매칭.
- 정규화는 하지 않음(train fold 기준 학습 시점).

---

## 작업 3-2 — 축 조합 교차표

| cook | flavor | prop | 전체 | positive |
|:---:|:---:|:---:|---:|---:|
| 1 | 1 | 1 | 689 | **218** |
| 1 | 1 | 0 | 683 | 85 |
| 1 | 0 | 1 | 13 | 1 |
| 1 | 0 | 0 | 29 | 0 |
| 0 | 1 | 1 | 364 | 77 |
| 0 | 1 | 0 | 168 | 23 |
| 0 | 0 | 1 | 377 | 34 |
| **0** | **0** | **0** | **1,373** | **65** |

3축 완비(1·1·1)가 689쌍으로 늘었고 positive의 43%(218/503)가 여기 몰립니다.

### ⚠️ 세 축 모두 부재: 1,373쌍 (positive 65) — 핵심 지표, 유지

완화 후 1,451 → **1,373쌍(39.3% → 37.2%)** 으로 소폭 줄었습니다(귀경 완화 반영).
**축소하지 않고 유지**합니다 — 사용자 결정대로, 축소 기준이 전통 축 커버리지에 의존하면
순환이 되고 availability mask의 존재 이유가 사라지기 때문입니다.

관련 후보 125종: 서양 식재(블랙커런트·프로슈토·안초비·러비지), 복합조미(오향분·가람마살라·
해선장), 치즈류(체더·블루·부라타), 육수·유지, 월계수, 대추야자 등. 대부분 herb 14개 전체에서
부재라 큰 덩어리를 만듭니다.

---

## 작업 3-3 — herb별 커버리지

| herb | cook | flavor | prop | positive |
|---|---:|---:|---:|---:|
| 강황~회향 (13개) | 38% | 52% | **42%** | 28~43 |
| **월계수** | 38% | 52% | **0%** | 31 |

월계수만 prop=0(본초 미수재, 정상). 나머지는 완화로 31%→42% 상승.

---

## 작업 3-4 — 라벨 분포

| | positive 수 | 비율 |
|---|---:|---:|
| Claude | 279 | 7.55% |
| Llama | 275 | 7.44% |
| GPT | 278 | 7.52% |
| **셋 중 하나라도** | **503** | **13.61%** |

---

## 작업 4 — 판정

> **positive 쌍의 mask_prop = 65.6% ≥ 60% → 전통 축 정상 작동. 264 후보 그대로 진행.**

완비 기준 완화로 조건부(53.3%)에서 정상(65.6%)으로 올라섰습니다. 축소하지 않습니다.

---

## 산출물

| 파일 | 내용 |
|---|---|
| `output/exp1_dataset.csv` | 3,696행 × 23컬럼 (분할 마스크·결측 컬럼 포함) |
| `output/exp1_coverage.md` | 본 리포트 |
| `output/_exp1_stats.json` / `_exp1_meta.json` | 원시 수치 (pos_weight 포함) |

최종 학습 데이터는 `final/` 폴더에 별도 정리했습니다(§ FINAL.md 참조).

재현: `exp1_00_probe.py` → `exp1_01_build.py` → `exp1_03_diag.py` → `exp1_02_stats.py`
